### ISSUE TITLE
Internet Explorer 11 Error

### ISSUE THREAD

**Issue by e-rocky** [WeAreAthlon/frontend-webpack-boilerplate#33]
None of the websites i created using the frontend-webpack-boilerplate are working on IE11

I tried to figure out why I get this issue and I ended up installing a fresh version of the latest boilerplate but i still get the same 
error message : app.js (1,4) syntax error

1. install the latest version of the boilerplate
2. install all the dependencies
3. run yarn dev
4. open in IE11

![Capture d’écran 2021-06-02 145407](https://user-images.githubusercontent.com/23634037/120475846-8ea97f80-c3b2-11eb-8d05-913be9b6bef5.png)

No js is working due to this error

the error is even visible in your demo page
https://weareathlon.github.io/frontend-webpack-boilerplate/

**Comment by pnikolov** [comment]
@e-rocky 
In order to support IE11 you should write IE11 compatible JS or you should configure such support for the `babel` ES6/7 transpiler(source-to-source compiler). 
The **current default settings** located in the `package.json` on line 7 are:
```js
{
  "browserslist": [
      "last 2 versions",
      "> 5%"
  ]
}
```
Which means the last 2 versions of the browsers that have usage more than `5%` on world basis. **IE11 does not fall in either to those criteria**. Browserslist uses [caniuse-lite](https://github.com/ben-eb/caniuse-lite) with [Can I Use](https://caniuse.com/) data for this queries.

You can add IE11 as supported browser for your project in the `browserlist` so _Babel_ can transpile your modern JS to the IE11 supported JS engine, here is the official documentation how to configure the supported browsers - [browserlist/browserlist](https://github.com/browserslist/browserslist)

Here is an example for `package.json` configuration, you should check the `browserlist` documentation for more examples:
```js
{
  "browserslist": [
      "last 2 versions",
      "> 5%",
      "IE >= 11",
  ]
}

**Comment by e-rocky** [comment]
> @e-rocky
> In order to support IE11 you should write IE11 compatible JS or you should configure such support for the `babel` ES6/7 transpiler(source-to-source compiler).
> The **current default settings** located in the `package.json` on line 7 are:
> 
> ```js
> {
>   "browserslist": [
>       "last 2 versions",
>       "> 5%"
>   ]
> }
> ```
> 
> Which means the last 2 versions of the browsers that have usage more than `5%` on world basis. **IE11 does not fall in either to those criteria**. Browserslist uses [caniuse-lite](https://github.com/ben-eb/caniuse-lite) with [Can I Use](https://caniuse.com/) data for this queries.
> 
> You can add IE11 as supported browser for your project in the `browserlist` so _Babel_ can transpile your modern JS to the IE11 supported JS engine, here is the official documentation how to configure the supported browsers - [browserlist/browserlist](https://github.com/browserslist/browserslist)
> 
> Here is an example for `package.json` configuration, you should check the `browserlist` documentation for more examples:
> 
> ```js
> {
>   "browserslist": [
>       "last 2 versions",
>       "> 5%",
>       "IE >= 11",
>   ]
> }
> ```
