### ISSUE TITLE
Not es2015

### ISSUE THREAD

**Issue by doublex** [WeAreAthlon/frontend-webpack-boilerplate#35]
````
git clone https://github.com/WeAreAthlon/frontend-webpack-boilerplate.git
cd frontend-webpack-boilerplate
npm install
npm run build
````

`dist/js/app.js` is not babeled to ES5, e.g. functions remain `() => ...`

**Comment by pnikolov** [comment]
@doublex 

In order to add support for ES5 you need to either target such browser version in the `browserslist` section in the `package.json` file of your project (recommended) or configure this support manually in the `.babelrc` file.

The default browser support list configuration shipped with this template is:
```js
"browserslist": [
  "last 2 versions",    
  "> 5%"
]
```

All browsers satisfying this criteria support ES6+ so, just add browser that support only lower than ES6 versions and babel will transpire your JS to ES5 to ensure browser support of the built `app.js` file.

Here is an example adding IE11 as supported, as it does not support ES6, the output will be using the `babel-preset-es2015`:

```js
"browserslist": [
  "last 2 versions",    
  "IE11",
]

**Comment by doublex** [comment]
Thanks a lot! You are right.
Sorry for disturbing.
