### ISSUE TITLE
How to handle html pages if i have more than 20 html pages?

### ISSUE THREAD

**Issue by creativeDM** [WeAreAthlon/frontend-webpack-boilerplate#36]
I want to manage more than 20+ html pages? Is there any shortcut using webpack html plugin?

**Comment by pnikolov** [comment]
@creativeDM 

Since [`v5.4.0`](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/releases/tag/v5.4.0) of this boilerplate template, all HTML files located in `src/` will be automatically processed, no need to configure or specify anything regarding the processing of the HTML files.

So just place all your 20 files in the `src/` directory and `webpack` will process them.

**Comment by tommypanagora** [comment]
Hello! I have a similar issue. I have placed my about.html in src but when I go to localhost:8000/about - I just get the error Cannot GET /about

**Comment by pnikolov** [comment]
@tommypanagora 

If you have named your page `about.html` and you are running the dev server on port `8000` the URL to the page is `localhost:8000/about.html`
