### ISSUE TITLE
Video Assets

### ISSUE THREAD

**Issue by doodirock** [WeAreAthlon/frontend-webpack-boilerplate#45]
Is there a place to place video assets to they will be copied over when we build?  There are a lot of landing pages where one might use and mp4 or webm.

**Comment by pnikolov** [comment]
@doodirock in order to have the referenced video files copied to the build (output) directory you can do the following:

1. Create a new directory e.g `videos` under `src/`
2. Place your video files in the newly created `src/videos/` directory
3. Update your `webpack.config.js` file and add new `CopyWebpackPlugin` `patterns` array item as follows:
    * Duplicate the existing defined pattern from lines `112 to 119`
    * Modify the duplicated pattern to specify the `videos` directory.

Here is the full `CopyWebpackPlugin` configuration that I used to test the video embedding:

```js
new CopyWebpackPlugin({
      patterns: [
        {
          from: path.resolve(environment.paths.source, 'images', 'content'),
          to: path.resolve(environment.paths.output, 'images', 'content'),
          toType: 'dir',
          globOptions: {
            ignore: ['*.DS_Store', 'Thumbs.db'],
          },
        },
        {
          from: path.resolve(environment.paths.source, 'videos'),
          to: path.resolve(environment.paths.output, 'videos'),
          toType: 'dir',
          globOptions: {
            ignore: ['*.DS_Store', 'Thumbs.db'],
          },
        },
      ],
    }),
```

After doing this, building your project will include all your video files.

**Comment by doodirock** [comment]
Fantastic thank for the help!
