### ISSUE TITLE
Files copied with CopyWebpackPlugin deleted in watch mode after first code modification

### ISSUE THREAD

**Issue by Wyzix33** [WeAreAthlon/frontend-webpack-boilerplate#5]
This repository's issues are reserved for mainly feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
After npm install i run 
```
npm run watch
```
and after the first file change and browser reload all the images copied by CopyWebpackPlugin get deleted...
it seems that if i remove the new CleanWebpackPlugin(), from plugins it's ok, but CopyWebpackPlugin  is not executed on code modifications...

I solved it for now by setting new CleanWebpackPlugin({ cleanStaleWebpackAssets: false }),
it's not ideal but i have to test some more...

* **What is the expected behavior?**

Images should all be recopied and available as they are before first modification

* **Please tell us about your environment:**
  
  - Version: 2.5.0
  - System / OS / Browser: [ Windows]
  - Language: [all | SASS | ES6/7 | ES5 ]

Thanks

**Comment by pnikolov** [comment]
@Wyzix33 thanks for the feedback, I will further investigate this behaviour and will update the configuration/documentation.

**Comment by pnikolov** [comment]
After a further research I found that the latest version of _Clean Webpack Plugin_ has this side effect/bug - [V2 dist folder content is deleted before webpack start building](https://github.com/johnagan/clean-webpack-plugin/issues/133) 

It seems to be fixed but it is not released yet. So until an official release I've released a new version of the boilerplate to use `v1.0.1` of the `clean-webpack-plugin` plugin instead of the latest `v2.0.2`. 

Here is the latest release containing this change together with a couple of new updates - [Release 2.6.0](https://github.com/WeAreAthlon/frontend-webpack-boilerplate/releases/tag/v2.6.0)
